### ISSUE TITLE
Security Issue - Do not compare with !==

### ISSUE THREAD

**Issue by jwagner** [AsoSunag/hmac-express#1]
Comparing the hmac using === is insecure as it allows timing attacks.
Use a constant time comparison function or do something like this:
https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/february/double-hmac-verification/

See for instance:
http://www.security-assessment.com/files/documents/presentations/TimingAttackPresentation2012.pdf

There is also a discussion about adding something to aid with this to node here:
https://github.com/nodejs/node-v0.x-archive/issues/8560

**Comment by AsoSunag** [comment]
Hi, thanks for your feedback!
